import {
  Activity,
  AirVent,
  AlarmClock,
  Anchor,
  Anvil,
  Apple,
  Archive,
  Axe,
  Baby,
  Banknote,
  Bath,
  Bed,
  Beer,
  Bell,
  Bike,
  Bird,
  Blinds,
  Blocks,
  Bolt,
  Book,
  BookOpen,
  Bookmark,
  Boxes,
  BrickWall,
  Briefcase,
  Brush,
  Building2,
  Bus,
  Cable,
  Cake,
  Calculator,
  Calendar,
  CalendarCheck,
  Camera,
  Car,
  Caravan,
  Carrot,
  Cctv,
  ChartLine,
  Church,
  Clapperboard,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cloud,
  Code,
  Coffee,
  Compass,
  Construction,
  Container,
  CreditCard,
  Database,
  Dog,
  DoorOpen,
  DoorStairwell,
  DraftingCompass,
  Drill,
  Droplet,
  Droplets,
  Drumstick,
  Dumbbell,
  Factory,
  Feather,
  Fence,
  FileCheck,
  FileText,
  Film,
  Fish,
  Flag,
  Flame,
  Flower2,
  Folder,
  Forklift,
  Fuel,
  Gamepad2,
  Gauge,
  Gift,
  Globe,
  GraduationCap,
  Guitar,
  Hammer,
  Handshake,
  HardHat,
  Headphones,
  Heart,
  HeartPulse,
  Home,
  Hourglass,
  HousePlus,
  Inbox,
  Key,
  LampCeiling,
  Landmark,
  Laptop,
  Layers,
  Leaf,
  Lightbulb,
  List,
  Lock,
  Luggage,
  Mail,
  Map,
  MapPin,
  MessageCircle,
  Mic,
  Milestone,
  Moon,
  Mountain,
  Music,
  NotebookPen,
  Nut,
  Package,
  PaintBucket,
  PaintRoller,
  Paintbrush,
  Palette,
  PartyPopper,
  PawPrint,
  Pencil,
  PencilRuler,
  Phone,
  Pickaxe,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  PlugZap,
  Puzzle,
  Receipt,
  Recycle,
  Rocket,
  Ruler,
  RulerDimensionLine,
  Salad,
  Scale,
  School,
  Scissors,
  Settings,
  Shield,
  Shirt,
  ShoppingCart,
  Shovel,
  ShowerHead,
  Smartphone,
  Snowflake,
  Sofa,
  Sparkles,
  Sprout,
  Star,
  Stethoscope,
  StickyNote,
  Store,
  Sun,
  Target,
  Tent,
  Thermometer,
  Ticket,
  Timer,
  TowerControl,
  ToyBrick,
  Tractor,
  TrafficCone,
  TreePine,
  Trees,
  Trophy,
  Truck,
  Umbrella,
  Users,
  Utensils,
  Video,
  Wallet,
  Wallpaper,
  Warehouse,
  Watch,
  Waves,
  Weight,
  Wifi,
  Wind,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export type IconGroup = {
  label: string;
  icons: { key: string; label: string; Icon: LucideIcon }[];
};

/**
 * Atslēgas (piem. "home") glabājas datubāzē, tāpēc tās nedrīkst mainīt.
 * Ikonu komponenti var brīvi apmainīt.
 */
export const ICON_GROUPS: IconGroup[] = [
  {
    label: "Ikdiena",
    icons: [
      { key: "list", label: "Saraksts", Icon: List },
      { key: "home", label: "Mājas", Icon: Home },
      { key: "briefcase", label: "Darbs", Icon: Briefcase },
      { key: "cart", label: "Pirkumi", Icon: ShoppingCart },
      { key: "lightbulb", label: "Idejas", Icon: Lightbulb },
      { key: "star", label: "Zvaigzne", Icon: Star },
      { key: "heart", label: "Sirds", Icon: Heart },
      { key: "flag", label: "Karogs", Icon: Flag },
      { key: "target", label: "Mērķis", Icon: Target },
      { key: "sparkles", label: "Dzirksteles", Icon: Sparkles },
      { key: "bell", label: "Zvans", Icon: Bell },
      { key: "bookmark", label: "Grāmatzīme", Icon: Bookmark },
      { key: "inbox", label: "Iesūtne", Icon: Inbox },
      { key: "archive", label: "Arhīvs", Icon: Archive },
      { key: "folder", label: "Mape", Icon: Folder },
      { key: "package", label: "Paka", Icon: Package },
    ],
  },
  {
    label: "Būvniecība",
    icons: [
      { key: "hardhat", label: "Ķivere", Icon: HardHat },
      { key: "construction", label: "Būvlaukums", Icon: Construction },
      { key: "brickwall", label: "Mūris", Icon: BrickWall },
      { key: "toybrick", label: "Ķieģelis", Icon: ToyBrick },
      { key: "blocks", label: "Bloki", Icon: Blocks },
      { key: "layers", label: "Slāņi", Icon: Layers },
      { key: "drill", label: "Urbjmašīna", Icon: Drill },
      { key: "shovel", label: "Lāpsta", Icon: Shovel },
      { key: "pickaxe", label: "Cērte", Icon: Pickaxe },
      { key: "axe", label: "Cirvis", Icon: Axe },
      { key: "anvil", label: "Lakta", Icon: Anvil },
      { key: "bolt", label: "Skrūve", Icon: Bolt },
      { key: "nut", label: "Uzgrieznis", Icon: Nut },
      { key: "pencilruler", label: "Rasējums", Icon: PencilRuler },
      { key: "draftingcompass", label: "Projektēšana", Icon: DraftingCompass },
      { key: "rulerdimension", label: "Izmēri", Icon: RulerDimensionLine },
      { key: "gauge", label: "Mērījumi", Icon: Gauge },
      { key: "weight", label: "Svars", Icon: Weight },
      { key: "forklift", label: "Iekrāvējs", Icon: Forklift },
      { key: "container", label: "Konteiners", Icon: Container },
      { key: "boxes", label: "Materiāli", Icon: Boxes },
      { key: "warehouse", label: "Angārs", Icon: Warehouse },
      { key: "factory", label: "Ražotne", Icon: Factory },
      { key: "towercontrol", label: "Tornis", Icon: TowerControl },
      { key: "caravan", label: "Vagoniņš", Icon: Caravan },
      { key: "trafficcone", label: "Konuss", Icon: TrafficCone },
      { key: "fence", label: "Žogs", Icon: Fence },
      { key: "houseplus", label: "Piebūve", Icon: HousePlus },
      { key: "milestone", label: "Etaps", Icon: Milestone },
      { key: "clipboardcheck", label: "Pieņemšana", Icon: ClipboardCheck },
      { key: "filecheck", label: "Akts", Icon: FileCheck },
    ],
  },
  {
    label: "Apdare un komunikācijas",
    icons: [
      { key: "paintroller", label: "Krāsošana", Icon: PaintRoller },
      { key: "paintbucket", label: "Krāsa", Icon: PaintBucket },
      { key: "paintbrush", label: "Krāsas ota", Icon: Paintbrush },
      { key: "wallpaper", label: "Tapetes", Icon: Wallpaper },
      { key: "dooropen", label: "Durvis", Icon: DoorOpen },
      { key: "stairwell", label: "Kāpnes", Icon: DoorStairwell },
      { key: "blinds", label: "Žalūzijas", Icon: Blinds },
      { key: "lampceiling", label: "Apgaismojums", Icon: LampCeiling },
      { key: "plugzap", label: "Elektrība", Icon: PlugZap },
      { key: "cable", label: "Kabelis", Icon: Cable },
      { key: "airvent", label: "Ventilācija", Icon: AirVent },
      { key: "thermometer", label: "Apkure", Icon: Thermometer },
      { key: "showerhead", label: "Santehnika", Icon: ShowerHead },
      { key: "droplets", label: "Ūdensvads", Icon: Droplets },
      { key: "cctv", label: "Novērošana", Icon: Cctv },
    ],
  },
  {
    label: "Māja un ģimene",
    icons: [
      { key: "sofa", label: "Dīvāns", Icon: Sofa },
      { key: "bed", label: "Gulta", Icon: Bed },
      { key: "bath", label: "Vanna", Icon: Bath },
      { key: "key", label: "Atslēga", Icon: Key },
      { key: "hammer", label: "Āmurs", Icon: Hammer },
      { key: "wrench", label: "Uzgriežņatslēga", Icon: Wrench },
      { key: "recycle", label: "Šķirošana", Icon: Recycle },
      { key: "baby", label: "Mazulis", Icon: Baby },
      { key: "dog", label: "Suns", Icon: Dog },
      { key: "pawprint", label: "Ķepa", Icon: PawPrint },
      { key: "bird", label: "Putns", Icon: Bird },
      { key: "flower", label: "Zieds", Icon: Flower2 },
      { key: "sprout", label: "Dīgsts", Icon: Sprout },
      { key: "leaf", label: "Lapa", Icon: Leaf },
      { key: "trees", label: "Koki", Icon: Trees },
      { key: "treepine", label: "Egle", Icon: TreePine },
    ],
  },
  {
    label: "Darbs un mācības",
    icons: [
      { key: "laptop", label: "Dators", Icon: Laptop },
      { key: "code", label: "Kods", Icon: Code },
      { key: "database", label: "Datubāze", Icon: Database },
      { key: "filetext", label: "Dokuments", Icon: FileText },
      { key: "clipboard", label: "Planšete", Icon: Clipboard },
      { key: "clipboardlist", label: "Kontrolsaraksts", Icon: ClipboardList },
      { key: "notebook", label: "Piezīmes", Icon: NotebookPen },
      { key: "stickynote", label: "Līmlapiņa", Icon: StickyNote },
      { key: "pencil", label: "Zīmulis", Icon: Pencil },
      { key: "ruler", label: "Lineāls", Icon: Ruler },
      { key: "chartline", label: "Grafiks", Icon: ChartLine },
      { key: "calculator", label: "Kalkulators", Icon: Calculator },
      { key: "handshake", label: "Sadarbība", Icon: Handshake },
      { key: "users", label: "Komanda", Icon: Users },
      { key: "graduationcap", label: "Studijas", Icon: GraduationCap },
      { key: "school", label: "Skola", Icon: School },
      { key: "book", label: "Grāmata", Icon: Book },
      { key: "bookopen", label: "Lasīšana", Icon: BookOpen },
      { key: "building", label: "Birojs", Icon: Building2 },
      { key: "settings", label: "Iestatījumi", Icon: Settings },
      { key: "shield", label: "Drošība", Icon: Shield },
      { key: "scale", label: "Juridiskais", Icon: Scale },
    ],
  },
  {
    label: "Nauda",
    icons: [
      { key: "wallet", label: "Maks", Icon: Wallet },
      { key: "banknote", label: "Nauda", Icon: Banknote },
      { key: "creditcard", label: "Karte", Icon: CreditCard },
      { key: "piggybank", label: "Krājumi", Icon: PiggyBank },
      { key: "receipt", label: "Čeks", Icon: Receipt },
      { key: "store", label: "Veikals", Icon: Store },
      { key: "landmark", label: "Banka", Icon: Landmark },
      { key: "tag", label: "Cena", Icon: Ticket },
    ],
  },
  {
    label: "Veselība un sports",
    icons: [
      { key: "dumbbell", label: "Treniņš", Icon: Dumbbell },
      { key: "activity", label: "Aktivitāte", Icon: Activity },
      { key: "heartpulse", label: "Veselība", Icon: HeartPulse },
      { key: "stethoscope", label: "Ārsts", Icon: Stethoscope },
      { key: "pill", label: "Zāles", Icon: Pill },
      { key: "bike", label: "Velo", Icon: Bike },
      { key: "trophy", label: "Kauss", Icon: Trophy },
      { key: "timer", label: "Taimeris", Icon: Timer },
    ],
  },
  {
    label: "Ēdiens",
    icons: [
      { key: "utensils", label: "Ēdiens", Icon: Utensils },
      { key: "coffee", label: "Kafija", Icon: Coffee },
      { key: "apple", label: "Ābols", Icon: Apple },
      { key: "carrot", label: "Burkāns", Icon: Carrot },
      { key: "salad", label: "Salāti", Icon: Salad },
      { key: "pizza", label: "Pica", Icon: Pizza },
      { key: "drumstick", label: "Gaļa", Icon: Drumstick },
      { key: "fish", label: "Zivs", Icon: Fish },
      { key: "cake", label: "Kūka", Icon: Cake },
      { key: "wine", label: "Vīns", Icon: Wine },
      { key: "beer", label: "Alus", Icon: Beer },
    ],
  },
  {
    label: "Ceļojumi un transports",
    icons: [
      { key: "plane", label: "Lidmašīna", Icon: Plane },
      { key: "car", label: "Auto", Icon: Car },
      { key: "bus", label: "Autobuss", Icon: Bus },
      { key: "truck", label: "Kravas auto", Icon: Truck },
      { key: "tractor", label: "Traktors", Icon: Tractor },
      { key: "fuel", label: "Degviela", Icon: Fuel },
      { key: "luggage", label: "Bagāža", Icon: Luggage },
      { key: "tent", label: "Telts", Icon: Tent },
      { key: "map", label: "Karte", Icon: Map },
      { key: "mappin", label: "Vieta", Icon: MapPin },
      { key: "compass", label: "Kompass", Icon: Compass },
      { key: "globe", label: "Pasaule", Icon: Globe },
      { key: "mountain", label: "Kalni", Icon: Mountain },
      { key: "waves", label: "Jūra", Icon: Waves },
      { key: "anchor", label: "Enkurs", Icon: Anchor },
      { key: "church", label: "Baznīca", Icon: Church },
    ],
  },
  {
    label: "Brīvais laiks",
    icons: [
      { key: "music", label: "Mūzika", Icon: Music },
      { key: "guitar", label: "Ģitāra", Icon: Guitar },
      { key: "headphones", label: "Austiņas", Icon: Headphones },
      { key: "mic", label: "Mikrofons", Icon: Mic },
      { key: "film", label: "Filma", Icon: Film },
      { key: "clapperboard", label: "Kino", Icon: Clapperboard },
      { key: "video", label: "Video", Icon: Video },
      { key: "camera", label: "Foto", Icon: Camera },
      { key: "gamepad", label: "Spēles", Icon: Gamepad2 },
      { key: "puzzle", label: "Puzle", Icon: Puzzle },
      { key: "palette", label: "Māksla", Icon: Palette },
      { key: "brush", label: "Ota", Icon: Brush },
      { key: "feather", label: "Spalva", Icon: Feather },
      { key: "gift", label: "Dāvana", Icon: Gift },
      { key: "party", label: "Svētki", Icon: PartyPopper },
      { key: "shirt", label: "Apģērbs", Icon: Shirt },
      { key: "scissors", label: "Šķēres", Icon: Scissors },
    ],
  },
  {
    label: "Cits",
    icons: [
      { key: "calendar", label: "Kalendārs", Icon: Calendar },
      { key: "calendarcheck", label: "Termiņš", Icon: CalendarCheck },
      { key: "clock", label: "Pulkstenis", Icon: Clock },
      { key: "alarmclock", label: "Modinātājs", Icon: AlarmClock },
      { key: "hourglass", label: "Smilšu pulkstenis", Icon: Hourglass },
      { key: "phone", label: "Zvani", Icon: Phone },
      { key: "smartphone", label: "Telefons", Icon: Smartphone },
      { key: "mail", label: "E-pasts", Icon: Mail },
      { key: "message", label: "Ziņas", Icon: MessageCircle },
      { key: "wifi", label: "Wi-Fi", Icon: Wifi },
      { key: "cloud", label: "Mākonis", Icon: Cloud },
      { key: "sun", label: "Saule", Icon: Sun },
      { key: "moon", label: "Mēness", Icon: Moon },
      { key: "wind", label: "Vējš", Icon: Wind },
      { key: "droplet", label: "Piliens", Icon: Droplet },
      { key: "snowflake", label: "Sniegpārsla", Icon: Snowflake },
      { key: "umbrella", label: "Lietussargs", Icon: Umbrella },
      { key: "flame", label: "Liesma", Icon: Flame },
      { key: "zap", label: "Enerģija", Icon: Zap },
      { key: "rocket", label: "Raķete", Icon: Rocket },
      { key: "lock", label: "Slēdzene", Icon: Lock },
      { key: "watch", label: "Rokas pulkstenis", Icon: Watch },
    ],
  },
];

const ICON_MAP: Record<string, LucideIcon> = Object.fromEntries(
  ICON_GROUPS.flatMap((g) => g.icons.map((i) => [i.key, i.Icon] as const)),
);

export const ICON_KEYS = Object.keys(ICON_MAP);

export function getIcon(key: string | null | undefined): LucideIcon {
  return (key && ICON_MAP[key]) || List;
}
